name: bikex
description: Buy the best bikes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  intl: ^0.20.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/images/
    - assets/icons/
